### ISSUE TITLE
[BUG] Tutorial 35: ValueError: Cannot subset columns with a tuple with more than one element.

### ISSUE THREAD

**Issue by huisky2000** [cgre-aachen/gemgis#301] opened 2023-09-07 07:13 UTC
**Describe the bug**

**To Reproduce**
1. https://gemgis.readthedocs.io/en/latest/getting_started/tutorial/35_plotting_borehole_data_with_pyvista.html
2. Follow the steps as described.
3. I got an error on step 12 (all steps before this are fine). 
labels = gg.visualization.create_borehole_labels(df=data)
labels
5. see below:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 1
----> 1 labels = gg.visualization.create_borehole_labels(df=data)
      2 labels

File ~\Anaconda3\envs\gemgis\lib\site-packages\gemgis\visualization.py:2375, in create_borehole_labels(df)
   2370     raise ValueError('X, Y and Altitude columns must be provided for label creation')
   2372 # Creating array with coordinates from each group (equals to one borehole)
   2373 coordinates = np.rot90(
   2374     np.array(
-> 2375         df.groupby(['Index', 'Name'])['X', 'Y', 'Altitude'].apply(lambda x: list(np.unique(x))).values.tolist()),
   2376     2)
   2378 # Creating borehole location PyVista PolyData Object
   2379 borehole_locations = pv.PolyData(coordinates)

File ~\Anaconda3\envs\gemgis\lib\site-packages\pandas\core\groupby\generic.py:1767, in DataFrameGroupBy.__getitem__(self, key)
   1763 # per GH 23566
   1764 if isinstance(key, tuple) and len(key) > 1:
   1765     # if len == 1, then it becomes a SeriesGroupBy and this is actually
   1766     # valid syntax, so don't raise
-> 1767     raise ValueError(
   1768         "Cannot subset columns with a tuple with more than one element. "
   1769         "Use a list instead."
   1770     )
   1771 return super().__getitem__(key)

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [e.g. Microsoft edge Version 116.0.1938.62 (Official build) (64-bit)]
 - Version [e.g. 116.0.1938.62]

**Additional context**

**Comment by AlexanderJuestel** [comment] 2023-09-07 08:17
@huisky2000 thanks for reporting this. I will have a look at it!

**Comment by AlexanderJuestel** [comment] 2023-09-07 09:22
Dear @huisky2000, 

I was able to fix the Issue. It was a ValueError caused by pandas>2.0.0, see https://stackoverflow.com/questions/76158147/pandas-groupby-valueerror-cannot-subset-columns-with-a-tuple-with-more-than-o

The bug is fixed in https://github.com/cgre-aachen/gemgis/pull/299/commits/902a9eafb4f7827c375b2f4f1e146ba2452b9c5a and will be published with GemGIS 1.1.1 very soon. 

Thanks for finding this! I will keep it upon until the PR is merged.

**Comment by huisky2000** [comment] 2023-09-11 07:33
Ok, thanks. The next question is how can i make the installation for GEMGIS 1.1.1?

**Comment by AlexanderJuestel** [comment] 2023-09-11 07:42
@huisky2000 I have not released GemGIS 1.1.1 yet. Once it is released, you can install it by `pip install gemgis`

**Comment by huisky2000** [comment] 2023-09-15 17:11
> @huisky2000 I have not released GemGIS 1.1.1 yet. Once it is released, you can install it by using `pip install gemgis` 

Ok, any workaround for now?

**Comment by AlexanderJuestel** [comment] 2023-10-03 07:33
@huisky2000 I have released GemGIS 1.1.1 and 1.1.2 just today. However, as we are currently changing the deployment process, you would have to pull the repo from Github to get the latest features

**Closed by AlexanderJuestel** 2023-10-03 07:33 UTC
